### ISSUE TITLE
text2vec-base-chinese-sentence cpu推理速度慢 正常吗

### ISSUE THREAD

**Issue by Dengyingjie** [shibing624/text2vec#101]
### Describe the Question
text2vec-base-chinese-sentence cpu推理速度较慢，16核，观察到cpu利用率也打满了，请问一个batch 512需要几十秒正常吗
唯一的改动是经过pca降维到128维了。
或者说有没有合适的batchsize建议。

**Comment by shibing624** [comment]
batchsize=16
