### ISSUE TITLE
"闵可夫斯基距离"错误

### ISSUE THREAD

**Issue by AnglesOf** [shibing624/text2vec#102]
[https://github.com/shibing624/text2vec/blob/master/text2vec/utils/distance.py#L44](url)
通过代码发现闵可夫斯基距离和欧氏距离的函数是相同的，并且闵可夫斯基距离公式计算是错误的，闵可夫斯基距离是一种定义。

**Comment by shibing624** [comment]
默认用的欧式距离算的，update。
