### ISSUE TITLE
对称语义还是非对称语义？

### ISSUE THREAD

**Issue by yufengzhe1** [shibing624/text2vec#103]
适用于对称语义检索的例子：

问题1：How to learn Python online?

答案1:How to learn Python on the web?

适用于非对称语义检索的例子：

问题2:What is Python？

答案2:Python is an interpreted, high-level and general-purpose programming language. Python’s design philosophy …”

**Comment by yufengzhe1** [comment]
如上，请问训练的时候是对称语义还是非对称语义？langchain➕大模型搭建外挂知识库，需要用到对句子的编码，问题匹配。实际更希望是非对称语义检索的例子：

问题2:What is Python？

答案2:Python is an interpreted, high-level and general-purpose programming language. Python’s design philosophy …”请问该库中的模型是这样子的吗？

**Comment by shibing624** [comment]
multilingual是多语言对齐的模型。
