### ISSUE TITLE
TypeError: get_sentence_examples() missing 1 required positional argument: 'prefix'

### ISSUE THREAD

**Issue by gdh756462786** [shibing624/text2vec#11]
TypeError: get_sentence_examples() missing 1 required positional argument: 'prefix'

	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]]

大佬，我在用bertsim时出现这个错误，是跟tensorflow版本有关系？

**Comment by shibing624** [comment]
你用的哪个版本tf？我测试是tf-1.14

**Comment by gdh756462786** [comment]
我之前是tf-2.0,我用1.14版本跑一下，谢谢哈

**Comment by gdh756462786** [comment]
好像还是不行，是这个函数报错：def get_sentence_examples(self, questions, prefix):　是没有给这个参数赋值
