### ISSUE TITLE
The difference between STSB and STSBenchmark

### ISSUE THREAD

**Issue by staoxiao** [shibing624/text2vec#111]
您好， 请问一下您发布的数据集STSB(1.36k rows) (https://huggingface.co/datasets/shibing624/nli_zh/viewer/STS-B/test)为什么与STSBenchmark(https://huggingface.co/datasets/stsb_multi_mt/viewer/zh/test)数据集数量不同(1.38k rows)？您是做了什么过滤吗？

**Comment by shibing624** [comment]
自行对比。
