### ISSUE TITLE
使用中发现单机8卡的训练速度比sentense-transformer的速度慢。

### ISSUE THREAD

**Issue by sangyongjia** [shibing624/text2vec#114]
8卡使用text2vec中的 sentencebert模型，其训练速度比 单卡的sentense-transformer速度还慢（注：相同数量的训练数据）

不知道作者或其他使用者是否碰到过这个问题？

**Comment by shibing624** [comment]
没对比过，batch_size一样吗

**Comment by sangyongjia** [comment]
SentenceTransformer 使用的batch_size是64。

**Comment by sangyongjia** [comment]
> 没对比过，batch_size一样吗

有对比过text2vec的单卡和多卡训练速度的区别吗？看sentence_transformer issues中，其作者尝试dataparallel以支持并行训练时，性能并没有收益。
