### ISSUE TITLE
测评结果

### ISSUE THREAD

**Issue by Elisewyh** [shibing624/text2vec#118]
我使用您的脚本[tests/test_model_spearman.py]在p40下测试，没有复现出来评测结果，您能帮忙看看怎么回事吗？

model_name	encode_type	STS-B	ATEC	BQ	LCQMC	PAWSX	SOHU-dd	SOHU-dc	avg
text2vec-base-chinese	FIRST_LAST_AVG	0.921179368	0.2	0.298807152	0.866025404	0.115470054	0.69680998	0.438637106	0.505275581
text2vec-base-chinese	LAST_AVG	0.921179368	0.2	0.418330013	0.866025404	0.057735027	0.698363658	0.461319724	0.517564742
text2vec-base-chinese	CLS	0.837435789	-0.1	0.298807152	0.866025404	0.230940108	0.672736278	0.435530437	0.463067881
text2vec-base-chinese	POOLER	0.865350316	0.3	-0.179284291	0.692820323	0.057735027	0.495812678	0.194071247	0.346643614
text2vec-base-chinese	MEAN	0.893264842	0.2	0.358568583	0.866025404	0.173205081	0.700457487	0.447823608	0.519906429
text2vec-base-chinese-paraphrase	FIRST_LAST_AVG	0.879307579	0.5	0.836660027	0.866025404	0.577350269	0.771153503	0.621571281	0.721724009
text2vec-base-chinese-paraphrase	LAST_AVG	0.879307579	0.5	0.836660027	0.866025404	0.577350269	0.767288163	0.637887383	0.723502689
text2vec-base-chinese-paraphrase	CLS	0.688558316	0.4	0.478091444	0.577350269	0.461880215	0.701727277	0.546110893	0.550531202
text2vec-base-chinese-paraphrase	POOLER	0.446632421	0.4	0.298807152	0.519615242	0.346410162	0.563723704	0.393554815	0.424106214
text2vec-base-chinese-paraphrase	MEAN	0.879307579	0.5	0.836660027	0.866025404	0.75055535	0.76531092	0.639699763	0.74822272
text2vec-base-chinese-sentence	FIRST_LAST_AVG	0.865350316	0.5	0.717137166	0.866025404	0.577350269	0.694734627	0.460195945	0.668684818
text2vec-base-chinese-sentence	LAST_AVG	0.879307579	0.5	0.717137166	0.866025404	0.692820323	0.701333547	0.530489951	0.698159138
text2vec-base-chinese-sentence	CLS	0.781606737	0.5	0.776898596	0.808290377	0.519615242	0.512156235	0.198754203	0.585331627
text2vec-base-chinese-sentence	POOLER	0.795564	0.5	0.657375735	0.866025404	0.346410162	0.375155273	0.082185259	0.517530833
text2vec-base-chinese-sentence	MEAN	0.851393053	0.5	0.776898596	0.866025404	0.519615242	0.705212815	0.530814109	0.678565603

**Comment by shibing624** [comment]
没看到问题重点是啥？差多少，哪个方法差？

**Comment by Elisewyh** [comment]
> 没看到问题重点是啥？差多少，哪个方法差？

就是跑出来的结果和你这个测评报告里的结果差异很大 https://huggingface.co/shibing624/text2vec-base-chinese
