### ISSUE TITLE
Text Matching task: error: unrecognized arguments: --fp16

### ISSUE THREAD

**Issue by rangehow** [shibing624/text2vec#119]
### Describe the Question
求助，在readme的脚本里我看到了一个`CUDA_VISIBLE_DEVICES=0,1 torchrun --nproc_per_node 2  training_sup_text_matching_model_mydata.py --do_train --do_predict --output_dir outputs/STS-B-text2vec-macbert-v1 --batch_size 64 --fp16 --data_parallel 
` 但是当我运行这个指令的时候，--fp16弹出了错误，如题所示，应该怎么解决呢？

**Comment by shibing624** [comment]
fixed，如果GPU机器支持bf16，可以加上bf16的参数。
