### ISSUE TITLE
能否测试LLM大规模语言模型计算出的text vector 是否能大幅度提高语义匹配的精度

### ISSUE THREAD

**Issue by yangkequn** [shibing624/text2vec#128]
- [ ✅] I checked to make sure that this is not a duplicate issue

### Describe the solution you'd like
现在llama2 这样的ChatGPT开源等效可以计算语义Vector.
比如国内最先进的模型之一baichuan2.
在 https://hub.docker.com/ 可以下载docker image
shaowenchen/baichuan2-7b-chat-gguf:Q4_0
在其/docs中就提供了计算语义的Demo

我期望能评估大模型对语义性能的提升。毕竟这是最新的技术。用一千倍左右的计算量。我期望可以用这个最先进，耗费最多智力投入的技术带来显著重大的语义计算性能的提升

**Comment by shibing624** [comment]
baichuan2不能提高语义匹配的精度，建模方法又不是匹配用的。
