### ISSUE TITLE
v1.2.0优化细节咨询

### ISSUE THREAD

**Issue by MingFL** [shibing624/text2vec#130]
release中描述切换到了ERNIE3.0-base，有单独做消融实验对比 bert-chinese吗
我们在非开源的相关性数据集上曾经对比过两者，似乎ERNIE3.0并不能提升spearman，而且收敛后的结果pearson和mse的指标也相对差一些，这里是在公开数据集上消融验证了ERNIE3.0的优异性么

**Comment by shibing624** [comment]
有消融实验。https://github.com/shibing624/text2vec/blob/master/docs/model_report.md#43-basemodel%E9%80%89%E6%8B%A9%E7%9A%84%E5%AE%9E%E9%AA%8C%E5%88%86%E6%9E%90

**Comment by MingFL** [comment]
实验分析记录很赞
