### ISSUE TITLE
text2vec-base-multilingual 向量维度可以从 384 调整到 768 吗

### ISSUE THREAD

**Issue by dingcb** [shibing624/text2vec#138]
修改了 config.json 文件中的参数
"hidden_size": 768,
运行时出现如下错误:
![image](https://github.com/shibing624/text2vec/assets/7745352/8399a404-6a38-46f2-b46f-242c37cb182a)

**Comment by shibing624** [comment]
为啥修改？ 要修改emb size, 需要重新训练模型。

**Comment by dingcb** [comment]
> 为啥修改？ 要emb尺寸，需要重新训练修改模型。
因为我们有使用 text2vec-base-chinese-sentence ，想把他们的维度改为一样。
现在知道为什么不能修改了，谢谢
