### ISSUE TITLE
模型微调卡住

### ISSUE THREAD

**Issue by CathyKitten** [shibing624/text2vec#139]
想请问一下，用python training_sup_text_matching_model_jsonl_data.py --model_arch cosent --do_train --do_predict --num_epochs 10 --model_name hfl/chinese-macbert-base --output_dir ./outputs/STS-B-cosent命令跑的时候，会停在下面这个界面一段时间吗。跑的速度会比较慢吗。
![image](https://github.com/shibing624/text2vec/assets/87537946/d1aefac5-f8d7-4db0-bb2b-7b848f93002a)

**Comment by shibing624** [comment]
不是bug，cpu训练bert类模型极慢。
