### ISSUE TITLE
关于导入本地词向量的问题

### ISSUE THREAD

**Issue by q2044757581** [shibing624/text2vec#14]
我下载了词向量到本地，怎么自定义词向量路径

**Comment by yaya159456** [comment]
兄弟 你下载的哪个词向量文件 给个链接好吗

**Comment by shibing624** [comment]
建议用腾讯的官方公布词向量，如果是自己训练的也可以加载。

**Comment by edwardLui** [comment]
我已下载了腾讯的官方公布词向量，如何使用？

**Comment by shibing624** [comment]
轻量版腾讯词向量，二进制，111MB放到 ~/.text2vec/datasets/light_Tencent_AILab_ChineseEmbedding.bin 即可。

腾讯词向量, 6.78G放到： ~/.text2vec/datasets/Tencent_AILab_ChineseEmbedding.txt

**Comment by FlashZdy** [comment]
出现 Downloading data from https://www.borntowin.cn/mm/emb_models/light_Tencent_AILab_ChineseEmbedding.bin
后就报错了，这个网址不能访问到。请问应该如何解决？

**Comment by FlashZdy** [comment]
> 兄弟 你下载的哪个词向量文件 给个链接好吗

手动下载可参考这篇博客
https://blog.csdn.net/BTUJACK/article/details/98477060

**Comment by s1162276945** [comment]
> 出现 Downloading data from https://www.borntowin.cn/mm/emb_models/light_Tencent_AILab_ChineseEmbedding.bin
> 后就报错了，这个网址不能访问到。请问应该如何解决？

github就能下载吧

**Comment by s1162276945** [comment]
> 轻量版腾讯词向量，二进制，111MB放到 ~/.text2vec/datasets/light_Tencent_AILab_ChineseEmbedding.bin 即可。
> 
> 腾讯词向量, 6.78G放到： ~/.text2vec/datasets/Tencent_AILab_ChineseEmbedding.txt

请问 text2vec 支持词向量的增量训练吗

**Comment by ripingit** [comment]
请问我如果想加载停用词表应该怎么处理？

**Comment by shibing624** [comment]
是指一句话中，过滤部分停用词，不计算其词向量吗？然后句子向量也忽略这些停用词的向量值？

**Comment by ripingit** [comment]
是的，实际训练里top 10的热词都是常用词，我需要将这部分词过滤掉

**Comment by lixihere** [comment]
> 轻量版腾讯词向量，二进制，111MB放到 ~/.text2vec/datasets/light_Tencent_AILab_ChineseEmbedding.bin 即可。
> 
> 腾讯词向量, 6.78G放到： ~/.text2vec/datasets/Tencent_AILab_ChineseEmbedding.txt

没有这个路径怎么办？我是菜鸟，能告诉我这个什么路径吗？

**Comment by Ziskan** [comment]
> > 轻量版腾讯词向量，二进制，111MB放到 ~/.text2vec/datasets/light_Tencent_AILab_ChineseEmbedding.bin 即可。
> > 腾讯词向量, 6.78G放到： ~/.text2vec/datasets/Tencent_AILab_ChineseEmbedding.txt
> 
> 没有这个路径怎么办？我是菜鸟，能告诉我这个什么路径吗？

c：/user/（你的用户名）/在这里面创建~/.text2vec/datasets/
你可以那个目录里面看见很多  .开头的文件
或者你可以找到text2vec的__init__文件，print里面的USER_DATA_PATH, 就可以找到目录了

**Comment by lixihere** [comment]
多亏了您的建议，问题已经解决。非常感谢！



crlx@163.com
 
发件人： Ziskan
发送时间： 2020-11-26 19:32
收件人： shibing624/text2vec
抄送： lixihere; Comment
主题： Re: [shibing624/text2vec] 关于导入本地词向量的问题 (#14)
轻量版腾讯词向量，二进制，111MB放到 ~/.text2vec/datasets/light_Tencent_AILab_ChineseEmbedding.bin 即可。
腾讯词向量, 6.78G放到： ~/.text2vec/datasets/Tencent_AILab_ChineseEmbedding.txt
没有这个路径怎么办？我是菜鸟，能告诉我这个什么路径吗？
c：/user/（你的用户名）/在这里面创建~/.text2vec/datasets/
你可以那个目录里面看见很多 .开头的文件
或者你可以找到text2vec的__init__文件，print里面的USER_DATA_PATH, 就可以找到目录了

**Comment by shibing624** [comment]
> 是的，实际训练里top 50的热词都是常用词，我需要将这部分词过滤掉
> [ DEBUG 20201110 08:55:27 word_embedding:136] Top 50 word : ['的', ',', '了', '“', '”', '是', '在', '和', '我', '有', '就', '也', '.', '你', '他', '都', '我们', '可以', '上', '一个', '啊', '与', '她', '个', '自己', '就是', '对', '这', '~', '为', '这个', '?', '还是', '等', '吗', '而', '到', '但', '将', '被', '没有', '他们', '-', '中', '但是', '吧', '从', '已经', '要', '呢']

1.add stopwords filter.  2. add custom stopwords file path. 
   https://github.com/shibing624/text2vec/commit/605f5a58c5d89e57689a21933dcf4d47e55a4ad1

**Comment by Hanqing1996** [comment]
@q2044757581 将自定义路径传入 Similarity 即可。参考自https://github.com/shibing624/text2vec/issues/5#issuecomment-586144424
```
from text2vec import Similarity

a = '如何更换花呗绑定银行卡'
b = '花呗更改绑定银行卡'
#
# sim = Similarity()
#
path = "light_Tencent_AILab_ChineseEmbedding.bin."
sim = Similarity(w2v_path=path)
s = sim.get_score(a, b)
print(s)
```

**Comment by Lxhnnn** [comment]
> 轻量版腾讯词向量，二进制，111MB放到 ~/.text2vec/datasets/light_Tencent_AILab_ChineseEmbedding.bin 即可。
> 
> 腾讯词向量, 6.78G放到： ~/.text2vec/datasets/Tencent_AILab_ChineseEmbedding.txt

我没有看到加载腾讯词向量txt的代码啊

**Comment by shibing624** [comment]
load_embedding: https://github.com/shibing624/text2vec/blob/master/text2vec/embeddings/word_embedding.py

**Comment by Lxhnnn** [comment]
> load_embedding: https://github.com/shibing624/text2vec/blob/master/text2vec/embeddings/word_embedding.py

这个只能加载bin模型，不能加载词向量.txt吧

**Comment by shibing624** [comment]
会改代码就都可以，不会的话就bin
