### ISSUE TITLE
关于模型的选择

### ISSUE THREAD

**Issue by Xiao-congxi** [shibing624/text2vec#140]
为什么推荐 text2vec-base-chinese 模型，它和 text2vec-base-chinese-paraphrase 相比哪个好？从测评结果看 text2vec-base-chinese-paraphrase 似乎效果更好？

**Comment by shibing624** [comment]
推荐又不是要求，哪个适合自己用哪个就好。

**Comment by Xiao-congxi** [comment]
非常感谢

**Comment by Xiao-congxi** [comment]
非常感谢~
