### ISSUE TITLE
相似度問題。

### ISSUE THREAD

**Issue by chunnan6666** [shibing624/text2vec#142]
### Describe the Question
Please provide a clear and concise description of what the question is.
請問兩個文本的相似度，可以作為作者的寫作風格的判定嗎?謝謝。

另外，對於相似度的成果呈現，除了%的數字之外，還能其它可視化圖形的方式表現嗎?

**Comment by shibing624** [comment]
1.没试过，理论上不行；
2.可以自行可视化
