### ISSUE TITLE
训练的loss一直为0，请问这是怎么回事

### ISSUE THREAD

**Issue by ann22** [shibing624/text2vec#146]
### Describe the Question
Please provide a clear and concise description of what the question is.
<img width="1081" alt="image" src="https://github.com/shibing624/text2vec/assets/28564507/4ea6f034-8d1d-48ac-b897-e11d8426a504">

**Comment by shibing624** [comment]
改loss了吗？看preds是正常的。

**Comment by ann22** [comment]
> 改loss了吗？看preds是正常的。

没改，直接在自己的数据上ft，bf16设置的FALSE，和这个有关吗

**Comment by shibing624** [comment]
1. maybe你数据有问题，看下数据格式和字段。2. 测试下demo样例数据的有问题不

**Comment by ann22** [comment]
> 1. maybe你数据有问题，看下数据格式和字段。2. 测试下demo样例数据的有问题不

1. 数据格式是：s1	s2	label；修改了数据后2-3 epoch loss就会变为0

**Comment by ann22** [comment]
请问用CoSENT方法训练，可以基于BAAI/bge-base-zh模型在中英文混合数据上FT吗

**Comment by shibing624** [comment]
可以
