### ISSUE TITLE
我该如何指定模型所在的位置，这样就不用到Hugging Face下载了

### ISSUE THREAD

**Issue by omaiyiwa** [shibing624/text2vec#153]
### Describe the Question
Please provide a clear and concise description of what the question is.

我该如何指定模型所在的位置，这样就不用到Hugging Face下载了
我现在是这样的，     self.m = BertSimilarity(model_name_or_path="shibing624/text2vec-base-chinese")

**Comment by shibing624** [comment]
"shibing624/text2vec-base-chinese" 改为模型绝对路径。

**Comment by omaiyiwa** [comment]
谢谢，我发现第一次下载完到本地后，之后如果不指定绝对路径，加载时间是778ms左右，如果加载绝对路径是470ms左右
