### ISSUE TITLE
能否在文档说下 text2vec.SentenceModel 和 SentenceTransformer 到底有什么区别？

### ISSUE THREAD

**Issue by qiulang** [shibing624/text2vec#154]
能否在文档说下 text2vec.SentenceModel 和 SentenceTransformer 到底有什么区别？

我试了readme 给的例子，发现他们计算出的示例句子的词向量是一样的。

**Comment by shibing624** [comment]
向量计算没区别，text2vec是中文模型的；SF是英文的。text2vec是适配cosent模型的训练，SF是其他的。

**Comment by qiulang** [comment]
我只是作为一个普通使用者，对NLP并不懂，但是看到 readme 写的 示例，比如银行卡那个，觉得对我好像没有太多说服力。所以我自己写了一个例子比较   "BAAI/bge-base-zh-v1.5"  和 "shibing624/text2vec-base-chinese"， 例子当然有点贻笑大方。

所以想请教一下，作为普通使用，我要怎么比较词嵌入的效果比较合适。 


```
import itertools

from sentence_transformers import SentenceTransformer
import torch

model = SentenceTransformer("BAAI/bge-base-zh-v1.5")
# model = SentenceTransformer("shibing624/text2vec-base-chinese")

facts = [
    "张三今年二十岁。",
    "张三今年一百斤。",
    "李四和娜娜是一对情侣。",
    "王五在医院上班。",
    "娜娜和兰兰是闺蜜。",
    "小明爱吃花椰菜。",
    "小明爱吃葡萄。",
    "小明不爱吃面条。",
    "小红的爱好是弹钢琴。",
    "小张正在修钢琴。",
    "刘老师是数学老师。",
    "张老师是体育老师。",
    "这个城市很多流浪汉。",
    "这个城市有高楼大厦。",
    "这个城市让人向往。",
]

queries = ["张三今年几岁？",
           "娜娜的男朋友是谁？",
           "谁是医生？",
           "小明喜欢吃什么水果？",
           "谁会弹钢琴？",
           "谁能讲讲这道题？",
           "这座城市有什么？"]

corpus_embeddings = model.encode(facts, convert_to_tensor=True)
query_embeddings = model.encode(queries, convert_to_tensor=True)

corpus_embeddings = util.normalize_embeddings(corpus_embeddings)
query_embeddings = util.normalize_embeddings(query_embeddings)

hits = util.semantic_search(
    query_embeddings, corpus_embeddings)

for i, (closest, *_) in enumerate(hits):
    print("Query:", queries[i], "Answer:", facts[closest["corpus_id"]])
```

**Comment by shibing624** [comment]
比较词嵌入的效果比较合适：拿业务数据，跑200条，看下相似检索匹配的准确率，可以取top3. 以医疗为例，医患的问答来匹配。

**Comment by qiulang** [comment]
不好意思，想再问一个问题，你的readme 里 Usage (HuggingFace Transformers) 说  First, you pass your input through the transformer model, then you have to apply the right pooling-operation on-top of the contextualized word embeddings.

这到底什么意思？

这也是我会给你开这个问题单的原因之一。我要得到一个句子的词嵌入，按readme 有三种方法，HuggingFace Transformers这个方法代码量最多，我又不懂有什么好处，所以就奇怪那为什么要用它。

**Comment by shibing624** [comment]
3个流行库，不同的人会使用不同的库，针对不同的开发者，本项目需要提供多种可用的调用方式。
