### ISSUE TITLE
SearchSimilarity相似句子检索疑问

### ISSUE THREAD

**Issue by hausofliufeng** [shibing624/text2vec#17]
作者您好，

在使用中发现了一个问题，当corpus所包含的句子比较多时，search_sim.get_scores(query)返回的概率列表有可能和corpus对应不上，维度会变少。

比如：
![image](https://user-images.githubusercontent.com/26713940/102948427-f3f26e00-4500-11eb-8251-7a406ca67334.png)

`
#sentences如下：
['原称《车骑出行》。',
 '画面从左至右为：四导骑，',
 '两两并排前行，',
 '骑手面相对，',
 '似交谈；',
 '三导骑，',
 '并排前行；',
 '二马轺车，',
 '轮有辐，',
 '车上一驭者执鞭，',
 '一尊者坐，',
 '回首；',
 '二导从，',
 '骑手面相对，',
 '似交谈；',
 '二马轺车，',
 '轮有辐，',
 '车上一驭者执鞭，',
 '一尊者坐；',
 '四导从，',
 '两两相对并排前行；',
 '两骑手，',
 '反身张弓射虎；',
 '虎，',
 '跃起前扑。',
 '上下右三边有框，',
 '上沿双边框内填刻三角纹，',
 '下沿双边框内填刻斜条纹。']`

**Comment by hausofliufeng** [comment]
猜测是不是因为corpus中一些句子长度过短，比如"虎，"，“回首；”，“似交谈；”等，被算法自动忽略了？

**Comment by shibing624** [comment]
原因是计算句子相似度时，会自动去重，28句例句中有5个重复的。
“
骑手面相对，
似交谈；
二马轺车，
轮有辐，
车上一驭者执鞭，
”

**Comment by hausofliufeng** [comment]
多谢多谢，明白了
