### ISSUE TITLE
关于SearchSimilarity类的使用

### ISSUE THREAD

**Issue by zhangqi8** [shibing624/text2vec#18]
我看到SearchSimilarity类只是使用了bm25算法去计算文本相似度top，请问使用(bm25或者编辑距离)+Word2Vec可以增加相识度判断的准确度吗，只是bm25不能对近似词做兼容

**Comment by ChunelFeng** [comment]
计算文本相似度，可以考虑用这个库： https://github.com/ChunelFeng/caiss
可以使用自定义距离的方式，来计算相似度

**Comment by zhangqi8** [comment]
Similarity类在计算文本相似度的时候没有用到词频，请问词向量计算的时候考虑词频会不会更准确点

**Comment by zhangqi8** [comment]
close
