### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '<!DOCTYPE'

### ISSUE THREAD

**Issue by tianke0711** [shibing624/text2vec#20]
### Describe the bug
> 112         w2v = KeyedVectors.load_word2vec_format(self.w2v_path, **self.w2v_kwargs, unicode_errors='ignore')
    113         # w2v = Word2Vec.load(self.w2v_path)
    114         # w2v.init_sims(replace=True)

~/anaconda3/lib/python3.7/site-packages/gensim/models/keyedvectors.py in load_word2vec_format(cls, fname, fvocab, binary, encoding, unicode_errors, limit, datatype, no_header)
   1630         return _load_word2vec_format(
   1631             cls, fname, fvocab=fvocab, binary=binary, encoding=encoding, unicode_errors=unicode_errors,
-> 1632             limit=limit, datatype=datatype, no_header=no_header,
   1633         )
   1634 

~/anaconda3/lib/python3.7/site-packages/gensim/models/keyedvectors.py in _load_word2vec_format(cls, fname, fvocab, binary, encoding, unicode_errors, limit, datatype, no_header, binary_chunk_size)
   1901         else:
   1902             header = utils.to_unicode(fin.readline(), encoding=encoding)
-> 1903             vocab_size, vector_size = [int(x) for x in header.split()]  # throws for invalid file format
   1904         if limit:
   1905             vocab_size = min(vocab_size, limit)

~/anaconda3/lib/python3.7/site-packages/gensim/models/keyedvectors.py in <listcomp>(.0)
   1901         else:
   1902             header = utils.to_unicode(fin.readline(), encoding=encoding)
-> 1903             vocab_size, vector_size = [int(x) for x in header.split()]  # throws for invalid file format
   1904         if limit:
   1905             vocab_size = min(vocab_size, limit)

ValueError: invalid literal for int() with base 10: '<!DOCTYPE'

### To Reproduce
Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) here. We hope we can simply copy/paste/run it. It is also nice to share a hosted runnable script (e.g. Google Colab), especially for hardware-related problems.

### Describe your attempts
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this is not a duplicate issue

You should also provide code snippets you tried as a workaround, StackOverflow solution that you have walked through, or your best guess of the cause that you can't locate (e.g. cosmic radiation).

### Context
 - **OS** [e.g. Windows 10, macOS 10.14]: 
 - **Hardware** [e.g. CPU only, GTX 1080 Ti]: 

In addition, figure out your version by running `import text2vec; text2vec.__version__`.

### Additional Information
Other things you want the developers to know.

**Comment by shibing624** [comment]
?

**Comment by shibing624** [comment]
没看懂问题描述哈，请给个可以复现问题的case

**Comment by tianke0711** [comment]
解决啦 谢谢
