### ISSUE TITLE
这是Similarity的bug吗请问？

### ISSUE THREAD

**Issue by Juddd** [shibing624/text2vec#24]
### Describe the Question
我随便弄了两个字符串试了下相似度的代码
```
a = "但就这一次而言，美国又是再一次试探两岸关系的底线。之前美国行政官员访问台湾，所乘坐的都是美国的行政专机。而这一次采用军机，显然是有意为之，从而展现出美国政府试图打台湾牌，挑衅大陆的决心。如果看看岛内的新闻报道，几乎都是一片欢呼之声，对“军机落地”进行了连篇累牍的报道。"
b = '核心就是这次三位美国国会议员前往台湾访问，他们所乘坐的是军用专机。机型据说是c17运输机，隶属于美国的太平洋空军。犹记得前几年美国军舰停泊在高雄，就引发了极大的舆论反弹。之后环球系也发表了评论，对美国军机军舰在岛内登陆，进行了严厉的“通牒”'

sim = Similarity()
s = sim.get_score(a, b)
print(s)
```

算出来的值是0.9536，这是不是有点夸张？完全不相似啊？请问这距离是做了归1处理处于(0,1)范围内的吗？

text2vec.__version__是0.1.9

**Comment by shibing624** [comment]
1.基于词粒度的语义判断，适用于短文本相似度计算。
2.这种长文本更多的是主题LDA判定，和句子语义不一致，适用于doc的similarity计算。

todo：调研，增加句子切分后，对短文本进行语义相似度计算，后加权求和给出长文本的相似度值。

**Comment by shibing624** [comment]
updated. version 0.2.0
