### ISSUE TITLE
requests.exceptions.SSLError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2

### ISSUE THREAD

**Issue by Lv5Electro** [shibing624/text2vec#35]
`sim = Similarity(similarity_type="cosine", embedding_type="sbert")`
使用上述代码运行后出现下载错误的提示，找了很多资料，好像是huggingface.co的下载URL出现了变化。
于是我尝试从本地读取，在新版的huggingface.co中下载了一个.bin模型，可还是报错，这次报错原因找了很久才找着是要读取一个vocab.txt才行。
请问有什么解决方法吗？

**Comment by shibing624** [comment]
新版的huggingface.co中下载了一个.bin模型？ 你为啥只下载一个bin，不下载全部文件夹呢？

**Comment by Lv5Electro** [comment]
> 新版的huggingface.co中下载了一个.bin模型？ 你为啥只下载一个bin，不下载全部文件夹呢？

感谢回复，我现在下完了所有文件，请问model_name_or_path的参数该填什么呢？我试着填包含了所有文件的那个路径，可是底层源码貌似规定必须是传一个文件才行。求指教！

**Comment by shibing624** [comment]
填模型文件夹的绝对路径
