### ISSUE TITLE
大量的文本搜索工作。有可能跟es或者一些非结构化的数据库一起使用吗

### ISSUE THREAD

**Issue by erichan2046** [shibing624/text2vec#40]
你好。请问可以加一些诸如跟es或者一些非结构的数据库一起使用的example吗

**Comment by shibing624** [comment]
1.可以，建议把text2vec的sentence model的vector导入milvus，或者es 7 等支持向量检索的搜索引擎使用。
2.我这边没写具体的使用搜索数据库的demo，可以直接参考官方示例https://milvus.io/bootcamp。
3.similarties库提供了基于hnsw的检索demo：https://github.com/shibing624/similarities/blob/main/examples/fast_sim_demo.py
