### ISSUE TITLE
预训练的模型会被下载到那个文件下

### ISSUE THREAD

**Issue by melowYX** [shibing624/text2vec#41]
### Describe the Question
我跑了一下demo，会下载一些预先训练的模型，请问下这些模型被下载后放到哪个文件下了

### Describe your attempts
- [ ] I walked through the tutorials
- [ ] I checked the documentation
- [ ] I checked to make sure that this is not a duplicate question

You may also provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) you tried as a workaround, or StackOverflow solution that you have walked through. (e.g. cosmic radiation).

In addition, figure out your version by running `import text2vec; text2vec.__version__`.

**Comment by shibing624** [comment]
shibing624/text2vec-base-chinese模型是CoSENT方法在中文STS-B数据集训练得到的，模型已经上传到huggingface的 模型库[shibing624/text2vec-base-chinese](https://huggingface.co/shibing624/text2vec-base-chinese)， 是text2vec.SentenceModel指定的默认模型，可以通过上面示例调用，或者如下所示用[transformers库](https://github.com/huggingface/transformers)调用， 模型自动下载到本机路径：~/.cache/huggingface/transformers
