### ISSUE TITLE
推测为pyechart版本所导致的报错

### ISSUE THREAD

**Issue by helixg** [shibing624/text2vec#43]
### Describe the bug
目前drawer部分的代码可能不太好用 pyecharts 0.5.11版本过老不太好装
`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_24056/869301412.py in <module>
----> 1 drawer.echarts_cate_draw(processed, processed["省"], "echarts_cate.html")

C:\ProgramData\Anaconda3\lib\site-packages\addressparser\drawer.py in echarts_cate_draw(locations, labels, file_path, title, subtitle, point_size)
     91         raise CPCAException("locations的长度与labels长度必须相等")
     92 
---> 93     from pyecharts import Geo
     94 
     95     geo = Geo(title, subtitle, title_color="#000000",

ImportError: cannot import name 'Geo' from 'pyecharts' (C:\ProgramData\Anaconda3\lib\site-packages\pyecharts\__init__.py)`

### Describe your attempts
我根据最新的版本对drawer部分进行了修改，把from pyecharts import Geo改成了from pyecharts.charts import Geo

但是依然抱错

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_18232/3391876356.py in <module>
      1 from addressparser import drawer
----> 2 drawer.echarts_draw(processed, "echarts.html")

C:\ProgramData\Anaconda3\lib\site-packages\addressparser\drawer.py in echarts_draw(locations, file_path, title, subtitle)
     63             count_map[map_key] = count_map.get(map_key, 0) + 1
     64 
---> 65     geo = Geo(title, subtitle, title_color="#fff",
     66               title_pos="center", width=1200,
     67               height=600, background_color='#404a59')

TypeError: __init__() got an unexpected keyword argument 'title_color'`

### Context
 - **OS** [e.g. Windows 11, macOS 10.14]: 
 - **Hardware** [CPU i9 9900kf GPU:RTX3080:]

**Comment by shibing624** [comment]
这个repo不需要安装pyechart。

请移到addressparser库。
