### ISSUE TITLE
未能复现readme中提到的测评结果

### ISSUE THREAD

**Issue by lcao1210** [shibing624/text2vec#44]
您好，跑了多次training_sup_text_matching_model.py，但是并没有复现您提到的测评结果，所有参数没有变化（包括种子节点），数据集使用STS-B，预训练模型使用macbert，测评结果如下，spearman并没有达到测评中的约0.8的效果（最大值为0.698），且loss一直是四点多，请问这是正常的吗？谢谢
global_step,train_loss,eval_spearman,eval_pearson
164,4.658605575561523,0.5426116932222851,0.47641591267918726
328,4.405113220214844,0.5439945238084548,0.5188740530814719
492,4.300437927246094,0.6474605061581004,0.5970089359751588
656,4.222658157348633,0.6981124011092907,0.6711254447604365
820,4.29534912109375,0.6530464719902352,0.6118443628723707
984,4.345531463623047,0.646561700736851,0.6159567799022208
1148,4.388575553894043,0.6697788748708465,0.6469002707405733
1312,4.2895097732543945,0.6617690364637314,0.6410338894857283
1476,4.244338035583496,0.6555082751093185,0.6330203079578507
1640,4.212394714355469,0.6574031992103613,0.6361311398830349

**Comment by shibing624** [comment]
可以复现。

`python training_sup_text_matching_model.py --num_epochs 10 --do_predict --output_dir ./outputs/bert-sup-stsb0615 --do_train`

```
> cat ./outputs/bert-sup-stsb0615/training_progress_scores.csv
global_step,train_loss,eval_spearman,eval_pearson
164,4.055016994476318,0.8294027263458963,0.8197754615019591
328,3.2892682552337646,0.8301803103425549,0.82227210140222
492,1.8474669456481934,0.8326155368225091,0.8225279741164652
656,1.8644722700119019,0.8365572378064113,0.8261353797572969
```

```
> cat ./outputs/bert-sup-stsb0615/eval_results.txt
eval_pearson = 0.8261353797572969
eval_spearman = 0.8365572378064113
```

**Comment by shibing624** [comment]
cosent模型

**Comment by lcao1210** [comment]
已复现，原因是我之前将cosent_model.py中的DataLoader的shuffle由False改为了True，改回之后就正常了
