### ISSUE TITLE
有现成的API可以直接调用吗？安装报错，计算句子相似度时：UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte，以及    raise OSError( OSError: Unable to load weights from pytorch checkpoint file for 'shibing624/text2vec-base-chinese' at '/home/jinxiaolong/.cache/huggingface/transformers/3827c3c09b5ee200704051f8692dc22ee340539c9da04b038dde4639afecb8ab.449ab5983a5a6414fac30737e0d44ee1a6e8e48ee422575640ec4d0302adac07'If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True. 还需要下载很多包

### ISSUE THREAD

**Issue by LeiyanGithub** [shibing624/text2vec#45]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte，以及    raise OSError( OSError: Unable to load weights from pytorch checkpoint file for 'shibing624/text2vec-base-chinese' at '/home/jinxiaolong/.cache/huggingface/transformers/3827c3c09b5ee200704051f8692dc22ee340539c9da04b038dde4639afecb8ab.449ab5983a5a6414fac30737e0d44ee1a6e8e48ee422575640ec4d0302adac07'If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True. 还需要下载很多包

**Comment by shibing624** [comment]
没有api，开源项目，开放底层技术，开发者自己搭建api服务。
