### ISSUE TITLE
first-last-avg和last-avg实现疑问

### ISSUE THREAD

**Issue by CaoYiwei** [shibing624/text2vec#46]
当前encoder_type为first-last-avg和last-avg时候，都是通过torch.avg_pool1d(last.transpose(1, 2), kernel_size=seq_length).squeeze(-1)实现的，seq_length不是真实长度，可能被补全。是不是应该考虑通过类似于mean的形式实现，统计有效文本长度？

**Comment by shibing624** [comment]
可以，但差别不大
