### ISSUE TITLE
有没有跟roformer比较下

### ISSUE THREAD

**Issue by yuanjie-ai** [shibing624/text2vec#48]
### Describe the Question
Please provide a clear and concise description of what the question is.

### Describe your attempts
- [ ] I walked through the tutorials
- [ ] I checked the documentation
- [ ] I checked to make sure that this is not a duplicate question

You may also provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) you tried as a workaround, or StackOverflow solution that you have walked through. (e.g. cosmic radiation).

In addition, figure out your version by running `import text2vec; text2vec.__version__`.

**Comment by shibing624** [comment]
我没有比较，大家可以再公开集上测试各模型效果。
