### ISSUE TITLE
有關中英文切詞

### ISSUE THREAD

**Issue by liphenyen** [shibing624/text2vec#50]
請問中英一起輸入模型的話，
輸入是
［"這個是python language"]
輸入sentenceBERt
他會怎麼切分進去模型？
英文會被切成p y t h o n這樣輸入進去嗎？
輸入multi-lingual
和 bert-base-Chinese
切法會不同嗎？
建議的輸入為何？

**Comment by shibing624** [comment]
切分依赖指定的tokenizer，传入对应的tokenizer可以改变切分方法。中英文一起建议用 bert-base-multilingual-cased ,会把英文切到wordpiece.
