### ISSUE TITLE
“中文匹配数据集的评测结果”和“本项目release模型的中文匹配评测结果”结果为什么差别那么大

### ISSUE THREAD

**Issue by Ramlinbird** [shibing624/text2vec#51]
不好意思打扰了，想问一下为什么readme里列出的“中文匹配数据集的评测结果”和“本项目release模型的中文匹配评测结果”
结果差异那么大，release模型怎么好像普遍低很多？是评测数据集不一样吗？谢谢~

**Comment by shibing624** [comment]
中文匹配数据集的评测结果，是针对每个数据集单独训练的模型。
