### ISSUE TITLE
请问training_unsup_text_matching_model_en是无监督训练吗？

### ISSUE THREAD

**Issue by caohangabc** [shibing624/text2vec#52]
小白真诚提问， 想使用作者大大的模型无监督fine-turn, 但 看到在 training_unsup_text_matching_model_en.py 里将label2int用于训练计算loss， 这不是无监督吧

**Comment by shibing624** [comment]
是无监督。This examples trains CoSENT model with the English NLI dataset, and predict in STS benchmark dataset.

在A模型上监督训练，用于B的预测，在B上评估。
