### ISSUE TITLE
长文本的相似度

### ISSUE THREAD

**Issue by xxllp** [shibing624/text2vec#54]
### Describe the Question
是否有支持长文本级别 相似度计算的模型

**Comment by shibing624** [comment]
模型不限制长度，可以支持长文本，训练时把max_length=512或者更长即可。

**Comment by xxllp** [comment]
现在提供的模型支持的长度是多少呢

**Comment by xxllp** [comment]
还有个问题 你这里能支持query doc 这种匹配模型吗

**Comment by shibing624** [comment]
1、自己从bert开始重新训练max_len=512，release的text2vec-base-chinese是max_len=128；
2、支持

**Comment by xxllp** [comment]
好的 看来现在的模型是不能满足我要求了
