### ISSUE TITLE
what if the sentence is longer than BERT default 512 ?

### ISSUE THREAD

**Issue by RedBlack888** [shibing624/text2vec#57]
Hi, 

If I want use the project to get the feature of sentences which is long, 
How could I use this project,.

As I use the pretrained model from [huggingface](https://huggingface.co/shibing624/text2vec-base-chinese), when the sentence comes longger. The following bug comes up. Do I need retrain the model?  
![image](https://user-images.githubusercontent.com/86508671/226322141-39780c45-cc81-49cb-a146-2cd9f3ef5b02.png)

Best.

**Comment by shibing624** [comment]
text2vec-base-chinese default max_seq_length: 128, if your sentence length > 128, you need retrain the model with your own dataset.
example: https://github.com/shibing624/text2vec/blob/master/examples/training_sup_text_matching_model_selfdata.py

**Comment by RedBlack888** [comment]
> text2vec-base-chinese default max_seq_length: 128, if your sentence length > 128, you need retrain the model with your own dataset. example: https://github.com/shibing624/text2vec/blob/master/examples/training_sup_text_matching_model_selfdata.py

Thanks for your advice. For a longer sentence, change `max_seq_length` argument and retrain on our own dataset.?

Best.

**Comment by shibing624** [comment]
yes

**Comment by RedBlack888** [comment]
> yes

Thanks,

If the sentence length > 512. Do I need to retrain bert model ?

Best.

**Comment by guantao18** [comment]
> > yes
> 
> Thanks,
> 
> If the sentence length > 512. Do I need to retrain bert model ?
> 
> Best.

Yes

**Comment by zbrnwpu** [comment]
> text2vec-base-chinese default max_seq_length: 128, if your sentence length > 128, you need retrain the model with your own dataset. example: https://github.com/shibing624/text2vec/blob/master/examples/training_sup_text_matching_model_selfdata.py

大神，您好，有个简单的问题想咨询下您？BERT模型的最长输入不是512么，text2vec-base-chinese 的max_seq_length怎么只有128，不应该是512么？我看您训练出了[text2vec-base-chinese-paraphrase]，这个仅支持输出256个中文长文本么？

**Comment by shibing624** [comment]
训练集分布，95%都是256字符内，我设的max length=256

**Comment by zbrnwpu** [comment]
> 训练集分布，95%都是256字符内，我设的max length=256

嗯呢，明白了，明神，我看您的s2p的数据集有些也很长，这些数据集您在训练的时候是怎么处理的那？我有一个数据集，70%的数据都在2000中文以上，想从您这儿取取经

**Comment by shibing624** [comment]
我这边是简单处理：截取前256 tokens
