### ISSUE TITLE
文本相似度

### ISSUE THREAD

**Issue by etrigger** [shibing624/text2vec#6]
请问，为什么有些句子根本不搭边，但是分数还是大于0.5
a = 你吃饭了吗 
b = 我会唱歌 
score = 0.7190231597933535# Similarity().get_score(a, b)

**Comment by shibing624** [comment]
模型是非监督的，句子之间的相似性，由于是用词拼接原因，会有一定的概率相近。所以文本相似度的比较在这里是一个相对的概念，不能那score去绝对的比较。
