### ISSUE TITLE
能在更多样本训练更准的模型吗

### ISSUE THREAD

**Issue by alexw994** [shibing624/text2vec#61]
另外，对这个结果有一点疑惑，这个是分别在每一个数据集上训练测试的结果吗？
<html>
<body>

Arch | Backbone | Model Name | ATEC | BQ | LCQMC | PAWSX | STS-B | Avg | QPS
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
CoSENT | hfl/chinese-macbert-base | CoSENT-macbert-base | 50.39 | 72.93 | 79.17 | 60.86 | 80.51 | 68.77

</body>
</html>

而下面的关于release模型的测试结果是只在STS-B上训练得到的？
<html>
<body>

Arch | Backbone | Model Name | ATEC | BQ | LCQMC | PAWSX | STS-B | Avg | QPS
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
CoSENT | hfl/chinese-macbert-base | shibing624/text2vec-base-chinese | 31.93 | 42.67 | 70.16 | 17.21 | 79.30 | 48.25 | 3008

</body>
</html>

最后就是数据集的5个part，可以混合训练吗？

**Comment by shibing624** [comment]
不可以，数据格式都不一样

**Comment by tiejunhu** [comment]
我试了一下，用一个类 "SuperDataset" 将所有的数据 concat 前后连接起来，是可以实现使用所有数据同时训练的，大致逻辑是：

```python
class SuperDataset:
    def __init__(self):
        self.datasets = []

    def add_dataset(self, dataset):
        self.datasets.append(dataset)

    def __len__(self):
        return sum([len(dataset) for dataset in self.datasets])

    def __getitem__(self, index):
        for dataset in self.datasets:
            if index < len(dataset):
                return dataset[index]
            index -= len(dataset)
```

**Comment by shibing624** [comment]
写代码适配也行的。点赞

**Comment by tiejunhu** [comment]
我用chinese-lert-base，基于所有的数据集，训练了一个模型在这里：https://huggingface.co/oldhu/text2vec-lert-base-5-tasks

测试的数据如下：

| STS-B | ATEC | BQ | LCQMC | PAWSX |
| ---- | ---- | ---- | ---- | ---- |
| 67.60 | 42.67 | 61.61 | 77.79 | 57.54 |

**Comment by shibing624** [comment]
嗯，我评估一下。

**Comment by shibing624** [comment]
算了一下，avg score: 61.44, 高于当前单任务训练的模型效果的。

考虑了一下，我这两天放出一个通用匹配模型，在更多数据上训练（百万、千万样本）的模型，然后能覆盖更多任务场景，还是不应该局限在这5个评估任务上。

另外，很多同学用 text2vec + langchain + chatglm6b 的技术路线做本地QA问答，此时相似文本召回也对text2vec的精度要求比较高，这里高准的通用模型也更重要。

**Comment by geolvr** [comment]
> 算了一下，avg score: 61.44, 高于当前单任务训练的模型效果的。
> 
> 考虑了一下，我这两天放出一个通用匹配模型，在更多数据上训练（百万、千万样本）的模型，然后能覆盖更多任务场景，还是不应该局限在这5个评估任务上。
> 
> 另外，很多同学用 text2vec + langchain + chatglm6b 的技术路线做本地QA问答，此时相似文本召回也对text2vec的精度要求比较高，这里高准的通用模型也更重要。

请问这个高准的通用模型现在放出了吗？

**Comment by shibing624** [comment]
放出来了， 是[shibing624/text2vec-base-chinese-sentence](https://huggingface.co/shibing624/text2vec-base-chinese-sentence)
