### ISSUE TITLE
服务器不能下载模型文件，请问可以手动上传那几个模型文件吗，上传到哪里呢

### ISSUE THREAD

**Issue by zhaoyiCC** [shibing624/text2vec#62]
m = CosentModel("bert-base-chinese") 不能联网，我只能自己上传，请问可以做到吗~ 谢谢

**Comment by shibing624** [comment]
上传到一个自己的文件夹，然后把 "bert-base-chinese" 改为文件夹的绝对路径就可以。

**Comment by zhaoyiCC** [comment]
好的，感谢~
