### ISSUE TITLE
wordembedding.embed计算的是每个单字的embedding而不是按照切好的词计算的

### ISSUE THREAD

**Issue by etrigger** [shibing624/text2vec#7]
a = "你好吗"

计算的是“你”，“好”，“吗”（(3, 1, 200) 的平均值）而不是“你好”，“吗”的平均值
问题可能是wordembedding.embed中出现的
        for sentence in sentence_list:
            emb = []

**Comment by shibing624** [comment]
你理解错误了，默认会切词的。结果是“你好”，“吗”的平均值。具体见测试case 
 https://github.com/shibing624/text2vec/commit/9fec1e29e87adce297acaa3a81b33a7297549be6。
