### ISSUE TITLE
label能否支持多档位呢[Feature] <title>

### ISSUE THREAD

**Issue by MingFL** [shibing624/text2vec#70]
### Is your feature request related to a problem? Please describe.

看到load_train_data里似乎将label约束为01的二分类问题了
但句向量往往具有多档位相关性，能否增加多档位的模块呢?

### Solutions

支持多档位loss

**Comment by MingFL** [comment]
看了下loss比较容易实现，所以不用了。

**Comment by shibing624** [comment]
label 本身可以写多档位，0,1,2,3,4,5 sts-b的label就是这样，loss算的是cos，都支持。
