### ISSUE TITLE
cos 值的疑惑

### ISSUE THREAD

**Issue by hanswang73** [shibing624/text2vec#72]
下面的问题，明显和文本中的第6行 ”《经开区关于开展“学宪法 讲宪法”系列活动的通知》，一、活动时间，2022年5月至12月。“ 更相似，但第 6 行的 cos 值却不是最小的（这里的 cos 值是用 scipy.spatial.distance.cosine 计算的，应该用1减了，值域是0~2），这是为什么？使用的用法有问题？还是文本都太长了，超过了 128 ？

【问题】---------------------------------------------------------------------------

活动时间是？

【cos值及文本】---------------------------------------------------------------------------

0.4966520812050492 《经开区关于开展“学宪法 讲宪法”系列活动的通知》，附件1，XX宪法学习教育活动总结一、2022年学习活动总体情况1.活动概况。请尽量用具体数字体现工作情况，如：组织XX名学生开展了XX场宪法教育活动等等……2.优秀选手选拔工作情况。主要介绍单位推荐选拔选手开展的工作二、工作亮点、典型案例或先进经验三、困难和问题四、2023年工作建议注：1.工作总结主张内容凝练、主题突出，字数不限。2.上述框架供参考，可根据各单位实际做调整。3.请盖章后提交扫描件。

0.4997463199625546 《经开区关于开展“学宪法 讲宪法”系列活动的通知》，五、主要活动，（三）国家宪法日“宪法晨读”活动。，结合第九个国家宪法日暨教育系统宪法学习周活动，教育部将于2022年12月上旬组织开展教育系统“宪法晨读”活动。国家宪法宣传周期间，市委教育工委市教委将组织全市教育系统各单位，通过设置分会场或参与网络直播等形式，组织开展“宪法晨读”活动。届时，有条件的学校，可通过教育部开通的网络视频直播通道，同步参与全国师生共同诵读宪法活动。

0.5288019589946925 《经开区关于开展“学宪法 讲宪法”系列活动的通知》，五、主要活动，（二）宪法知识竞赛和宪法演讲比赛，途径一：关注“丘瑞斯”微信公众号或“法治与校园”微信公众号，点击“当前活动”，进入“2022年北京市学生宪法知识竞赛”及“2022年北京市学生宪法演讲比赛”专区，参加活动。途径二：登录“丘瑞斯北京市学生在线活动平台”官网www.qiuruisi.com，进入“2022年北京市学生宪法知识竞赛”及“2022年北京市学生宪法演讲比赛”专区，参加活动。集体推荐学生均须通过以上任一途径在线参与宪法知识竞赛答题或提交宪法演讲视频。2022年10月，活动组委会统一组织全市学生“学宪法 讲宪法”决赛。全市决赛优胜者将代表北京参加全国总决赛。教育部普法网将于 2022年6月中旬开设学宪法、讲宪法“网络风采展示”平台。各区、各校可推荐本校宪法知识竞赛和宪法演讲比赛中的优胜选手，或鼓励动员更多优秀学生在完成“宪法卫士”行动计划达到相应要求后，自主通过平台开设的“个人通道”参与全国学生宪法活动海选和展示。教育部普法网将采用人工智能与专家评判相结合等方式，对参与学生的表现进行评价，为遴选北京市优秀选手提供参考。

0.5368339321656681 《经开区关于开展“学宪法 讲宪法”系列活动的通知》，五、主要活动，（一）争创“宪法卫士”活动。，继续组织好学生参加“宪法卫士”行动计划。各校要组织学生登录教育部全国青少年普法网（以下简称“教育部普法网”）第七届全国学生“学宪法 讲宪法”活动“宪法卫士”专栏，分学段完成宪法法治知识学习，获取“宪法卫士”标识。要早组织、早启动、早落实，通过学校统一组织和学生自主学习相结合，在校学生应当全员参与。各学校应在教师的组织指导下，依托思想政治理论课、法学专业课等课程教学，观看宪法学习视频并答题。各中小学校还可利用晨读、班会队会、综合实践活动、课后服务等时间统筹，指导学生登陆网站参加学习，推动形成人人争做“宪法卫士”的良好氛围。（教育部全国青少年普法网活动统筹：88819626；用户支持与新闻报送：88819614,88819617）

0.5372268743071114 《经开区关于开展“学宪法 讲宪法”系列活动的通知》，五、主要活动，（二）宪法知识竞赛和宪法演讲比赛，以纪念现行宪法公布施行四十周年为契机，组织动员经开区各类学校普遍开展宪法知识竞赛和宪法演讲比赛。在此基础上，按小学、初中、高中（含中等职业学校）、高校（含高等职业学校）分组，参与市级竞赛。取得教育部普法网“宪法卫士”标识的学生可通过集体推荐和个人自荐两种途径参加市级竞赛活动。1.集体推荐。各区、各校围绕我国宪法发展史、民法典、未成年人保护、预防未成年人犯罪、国家安全、劳动教育等主题，自行组织开展宪法知识竞赛和演讲比赛，认真做好选手推荐工作。宪法演讲中不可使用PPT、音乐、视频等多媒体素材，不可使用辅助道具，演讲时长为4至5分钟。学生演讲须脱稿，内容须原创，不可剽窃，否则将取消学生参赛资格及相关单位、指导教师评奖资格。2022年9月9日前，请各区遴选出小学组、初中组、高中组优秀学生各2人（每组知识竞赛1人、演讲比赛1人，共6人），各高校、职业学校、相关直属单位遴选出优秀学生2人（知识竞赛1人、演讲比赛1人），参加市级选拔、培训。2.个人自荐。自2022年7月11日起，所有学生均可通过以下途径参加全市学生宪法知识竞赛和宪法演讲比赛网络海选，展示自己宪法法治知识学习成效。网络海选中表现优异者将与集体推荐的选手一起参加市级选拔、培训。

0.544849097564879 《经开区关于开展“学宪法 讲宪法”系列活动的通知》，一、活动时间，2022年5月至12月。

0.548712070440063 《经开区关于开展“学宪法 讲宪法”系列活动的通知》，四、活动内容，（一）总体要求，2022 年“学宪法 讲宪法”活动，要以纪念现行宪法公布施行四十周年系列活动为主线，以深入学习宣传习近平法治思想为核心，与迎接党的二十大和学习宣传党的二十大精神相结合，着力提升针对性和实效性，增加活动的普及度和参与率，培养、增强学生的宪法意识和法治素养。

0.5604909911039611 《经开区关于开展“学宪法 讲宪法”系列活动的通知》，二、组织机构，主办单位：中共北京市委教育工作委员会、北京市教育委员会承办单位：北京教育融媒体中心、北京市青少年法治教育中心

0.5612918146405173 《经开区关于开展“学宪法 讲宪法”系列活动的通知》，六、材料报送，请各学校于2022年11月30日前报送各单位宪法学习教育活动总结电子版（总结格式详见附件1）。（“丘瑞斯”微信公众号二维码）（“法治与校园”微信公众号二维码）联系人及电话：白德柱 67832024   15901506951附件：1.XX宪法学习教育活动总结社会事业局2022年7月27日

0.5668012137257037 《经开区关于开展“学宪法 讲宪法”系列活动的通知》，三、参与对象，全市各普通中小学校、普通高等学校、职业学校（含民办学校）在校学生。

0.5764458630306888 《经开区关于开展“学宪法 讲宪法”系列活动的通知》，各学校：为深入学习贯彻习近平法治思想，推动青少年宪法学习宣传教育走深走实，根据《教育部办公厅关于组织开展第七届全国学生“学宪法 讲宪法”活动的通知》（教政法厅函〔2022〕5号）精神，市教委《关于组织开展2022年全市学生“学宪法 讲宪法”系列活动的通知》京教策【2022】7号相关安排，现将今年全市学生“学宪法 讲宪法”系列活动相关事项通知如下。

0.595521398683976 《经开区关于开展“学宪法 讲宪法”系列活动的通知》，四、活动内容，（二）学习重点，1.结合我国宪法发展史深化宪法教育。着重宣传现行宪法施行四十年来党重视用宪法法律维护人民群众合法权益、保障社会公平正义、推动国家发展进步的法治故事和案例。注重结合历史、国情和行为养成教育，重点宣传中国共产党的领导是中国特色社会主义最本质的特征、是中国特色社会主义制度的最大优势，引导青少年从小树立尊崇宪法的意识，进一步坚定听党话、跟党走的信念，厚植爱党爱国爱社会主义的情感。2.深入学习宣传习近平法治思想。将学习宣传贯彻习近平法治思想作为当前和今后一个时期青少年宪法法治教育的重要任务，推动习近平法治思想纳入国民教育体系，全面推进习近平法治思想进教材、进课程、进头脑。结合宪法学习宣传，以师生喜闻乐见的方式，宣传习近平法治思想的重大意义、丰富内涵、核心要义、精神实质、实践要求，进一步推动习近平法治思想贯彻落实到教育系统法治宣传教育的全过程和各方面。3.坚持与日常法治教育相结合。在宪法教育活动中增加民法典、教育法律法规、未成年人保护、国家安全、劳动教育等方面的法律知识，引导学生铸牢中华民族共同体意识，树立和巩固国家安全、诚实守信、规则意识等，了解掌握自我保护、防灾减灾救灾以及防范学生欺凌、网络诈骗、人身侵害等相关法律知识和技能。

**Comment by hanswang73** [comment]
用的是 huggingface 上下载的 text2vec-base-chinese 模型

**Comment by shibing624** [comment]
没懂，啥问题

**Comment by hanswang73** [comment]
【活动时间是？】这个句子，应该和【《经开区关于开展“学宪法 讲宪法”系列活动的通知》，一、活动时间，2022年5月至12月。】这个句子，语义最相似，但使用 huggingface 上下载的 text2vec-base-chinese 模型进行向量化后，计算下来，却不是这样

可能的原因，是因为文本太长了（超过了 128），还是其它原因 ？

**Comment by shibing624** [comment]
是文本太长了（超过了 128）

把多的句子截断或者分段算。

**Comment by hanswang73** [comment]
是否就是以下两种解决方案：

**Comment by hanswang73** [comment]
那是否就是以下两种解决方案？
1. 把长句分段算，然后求平均值
2. 自己按照512长度重新训练模型

**Comment by hanswang73** [comment]
这两种，您建议哪种？

**Comment by shibing624** [comment]
2

**Comment by hanswang73** [comment]
多谢！
