### ISSUE TITLE
有没有可能用较好7B中文预训练模型来contrasive train出一个s2p或p2p的embedding模型？

### ISSUE THREAD

**Issue by firezym** [shibing624/text2vec#79]
### Is your feature request related to a problem? Please describe.

大神好，遇到的问题还是较长的文本还有些表意问题，包括未来如果加入prompt来做similarity search，肯定需要foundation model很强。

### Solutions

现在看下来认真用较大比例中文语料搞的开源的，刚出来的baichuan-7B，看leaderboard表意的效果不错，有没有可能用这种7B的中文预训练模型来把contrasive train出一个sentence2paragraph或paragraph2paragraph的相似度embedding模型？

**Comment by shibing624** [comment]
直接调用sgpt的，输出sentence embedding就可以，不过评测其效果没  有监督训练的效果好。

**Comment by firezym** [comment]
嗯嗯，直接用效果直觉上就够呛，肯定需要在base model上再用监督训练一下的吧
