### ISSUE TITLE
text2vec仅仅是预训练模型将文本表示出向量吗？

### ISSUE THREAD

**Issue by 1264561652** [shibing624/text2vec#81]
你好，请问text2vec仅仅是预训练模型将文本表示成向量吗？

**Comment by shibing624** [comment]
是，本质是句子表征为向量矩阵。转换为向量后可以用于相似度计算，相似文本检索。

**Comment by 1264561652** [comment]
如果我想用它转换后的向量接着计算相似度该怎么操作呢？比如说我想用余弦相似度来计算文本相似度，那么我该如何将这个预训练模型和余弦相似度算法相结合？



---- 回复的原邮件 ----
| 发件人 | Ming Xu ***@***.***> |
| 日期 | 2023年06月20日 21:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [shibing624/text2vec] text2vec仅仅是预训练模型将文本表示出向量吗？ (Issue #81) |

是，本质是句子表征为向量矩阵。转换为向量后可以用于相似度计算，相似文本检索。

**Comment by shibing624** [comment]
看下readme
