### ISSUE TITLE
能用新闻分类的数据集做训练微调吗

### ISSUE THREAD

**Issue by tx-cslearn** [shibing624/text2vec#84]
### Describe your attempts
- [x] I walked through the tutorials
- [x] I checked the documentation
- [x] I checked to make sure that this is not a duplicate question

**Comment by shibing624** [comment]
可以，转0,1的label就行

**Comment by tx-cslearn** [comment]
> 可以，转0,1的label就行

是不是要改数据集啊，改成一行两个句子的那种，然后后面0 1 是否相似
有没有可以转换数据的脚本呢

**Comment by shibing624** [comment]
自己写吧

**Comment by xxllp** [comment]
我想问下 这种用相似度进行文本分类的是否在小样本时候有一些优势
