### ISSUE TITLE
w2v-light-tencent-chinese对文本是否有长度限制呢？

### ISSUE THREAD

**Issue by graciechen** [shibing624/text2vec#85]
### Describe your attempts
- [ ] I walked through the tutorials
- [ ] I checked the documentation
- [ ] I checked to make sure that this is not a duplicate question

w2v-light-tencent-chinese对文本是否有长度限制呢？

**Comment by shibing624** [comment]
没，是简单取平均算得句子得分。一般不建议太长，max_len=128为好
