### ISSUE TITLE
为什么不对 embedding 做归一化呢？

### ISSUE THREAD

**Issue by thsno02** [shibing624/text2vec#87]
### Describe the Question

在阅读 https://github.com/shibing624/text2vec/blob/master/docs/model_report.md#22-sentence-bert%E6%A8%A1%E5%9E%8B 中有一个疑问。在我的理解里，通常都需要对 embedding 做归一化，然后使用归一化的 embedding 作为最终的结果来计算 similarity。但如果按照这个思路，文章中的 | u - v  | 的操作就失去意义了。

我在网上搜索了一些信息，比如 https://stats.stackexchange.com/questions/177905/should-i-normalize-word2vecs-word-vectors-before-using-them 中提到：

>A word that is consistently used in a similar context will be represented by a longer vector than a word of the same frequency that is used in different contexts.

但也有很多关于使用 normalized embedding 提高模型表现的，比如 https://arxiv.org/abs/1911.03918

我不太清楚什么时候应该对 embedding 进行归一化，什么时候不进行归一化？以及为什么在现有的 embedding model 中，不进行归一化是一个更主流的方案？

**Comment by shibing624** [comment]
dot-product 要做归一化，cos 不用，cos + 归一化等效于dot-product

**Comment by thsno02** [comment]
我之前主要是对

>而监督方法的直接做法是u - v后面接一个全连接层的分类器，但交叉熵的分类器是基于内积计算的，它没法区分两个分布在不同球面的类别，所以这里加上绝对值变成|u - v|，将球面变成锥形，此时就可以用分类器来做分类了。

中的做差后求模长的操作比较困惑。不过我后来想了一下，使用 |u-v| 这种形式可能是“试出来”的，因为消融实验里给了别的选项。个人理解是，使用差值能保留 embedding 更多的信息，至于在 BERT 里是哪些信息就不是很清楚了。

查了一些资料，比如：

+ https://stackoverflow.com/questions/36034454/what-meaning-does-the-length-of-a-word2vec-vector-have/50550236#50550236 表明在 word2vec 中模长会包含一些 word frequency 的信息；
+ https://www.zhihu.com/question/318407108 这里比较了一下 dot-product 和 cosine。

在最终计算 similarity 的时候，看场景选用 metric 吧。

PS：dot-product + 归一化等效于 cosine 吧？
