### ISSUE TITLE
文档中第三个query-doc查询的例子，是用bm25算法计算的吗？为什么第二篇文档相似度这么低？

### ISSUE THREAD

**Issue by DaveGeneral** [shibing624/text2vec#9]
凭感觉看相似度的话第二个句子应该得很高的分数呀，如下：
['如何更换花呗绑定银行卡', '花呗更改绑定银行卡', '我什么时候开通了花呗']
如何更换花呗绑定银行卡 scores: [ 0.9527457  -0.07449248 -0.03204909]
如何更换花呗绑定银行卡 rank similarities: ['如何更换花呗绑定银行卡', '我什么时候开通了花呗', '花呗更改绑定银行卡']

**Comment by shibing624** [comment]
bm25_rank 计算的。
