### ISSUE TITLE
m芯片使用cpu的模式也会出现Torch not compiled with CUDA enabled’的错误

### ISSUE THREAD

**Issue by stoneLee81** [shibing624/text2vec#90]
m1max芯片，
调用ChatGlmModel(gen_model_type, gen_model_name_or_path, use_cuda=False，peft_name=lora_model_name_or_path) 指定cpu执行，但也会抛出 ‘Torch not compiled with CUDA enabled’的错误。
debug代码发现，在这段代码，mps.is_available会执行为true
<img width="602" alt="image" src="https://github.com/shibing624/text2vec/assets/18001708/c9c4a45f-d83b-437e-a98a-557afccd3efe">
导致fp16_support代码会执行，
如果将代码注释掉，强制执行cpu
<img width="422" alt="image" src="https://github.com/shibing624/text2vec/assets/18001708/ae0551e7-c2af-4ae5-96e3-ccf8b0d73553">
<img width="646" alt="image" src="https://github.com/shibing624/text2vec/assets/18001708/5018a07f-bcde-439b-aa53-71cc42566fb4">
这段逻辑也是true，一样会执行cuda的检查

**Comment by shibing624** [comment]
安装cpu的torch吧

**Comment by stoneLee81** [comment]
抱歉，我刚学习这块，pytorch在mac不是只有一个default的安装模式么，win才有cpu/gpu的安装选择吧
