### ISSUE TITLE
请问无监督的训练数据是如何构建的呢 examples/training_unsup_text_matching_model_en.py

### ISSUE THREAD

**Issue by mzdsk2** [shibing624/text2vec#91]
请问这个例子中 example: [examples/training_unsup_text_matching_model_en.py](https://github.com/shibing624/text2vec/blob/master/examples/training_unsup_text_matching_model_en.py) 

无监督的训练数据，用于CoSENT损失函数的时候，是如何设计的呢

**Comment by shibing624** [comment]
就是迁移学习。
