### ISSUE TITLE
Question about training sample 

### ISSUE THREAD

**Issue by callanwu** [shibing624/text2vec#92]
### Describe the Question
If I only have approximately 2,000 labeled training samples containing values of 0 and 1, how can I effectively fine-tune a Word2Vec model based "shibing624/text2vec-base-chinese" ? Can it still yield useful results?

**Comment by programmeguru** [comment]
I think it may not better than result of not fine-tuning

**Comment by callanwu** [comment]
right, it got worse results after fine-tuning.

**Comment by callanwu** [comment]
thanks for yr reply!

**Comment by programmeguru** [comment]
welcome~
