### ISSUE TITLE
AttributeError: ''NoneType object has no attribute 'squeeze' 

### ISSUE THREAD

**Issue by mzdsk2** [shibing624/text2vec#93]
### Describe the bug
`AttributeError: ''NoneType object has no attribute 'squeeze' `
出现了这个错误，貌似是使用了其他的BERT模型，运行cosent 训练， 请问只能局限通用的BERT吗

**Comment by shibing624** [comment]
其他的BERT模型？

**Comment by mzdsk2** [comment]
@shibing624 找到原因了，这个模型的 inputs 的keys是dict_keys(['input_ids', 'attention_mask'])

**Comment by mzdsk2** [comment]
有的模型没有token_type_ids ,这导致了错误，可以修改consent_model.py
```python 
if "token_type_ids" not in inputs:
   token_type_ids = None 
else:
   token_type_ids = inputs.get('token_type_ids').squeeze(1).to(self.device)```

**Comment by shibing624** [comment]
fixed.
