### ISSUE TITLE
训练数据正负样本的比例

### ISSUE THREAD

**Issue by baisuzi** [shibing624/text2vec#97]
### Describe the Question
我在垂域数据上构造了一个label只有0，1标签的二分类数据集，在此数据集上训练CoSENT模型，正负样本的比例能够达到1:80，因为训练一次时间比较久，想请教一下正负样本比例相差太大是否反而会降低训练的效果呢，大家的经验是比例控制在多少比较好呢

**Comment by shibing624** [comment]
1:1
