### ISSUE TITLE
文件的分割，text2vec-base-chinese支持最大输入tokens是128

### ISSUE THREAD

**Issue by stoneLee81** [shibing624/text2vec#98]
如果最大input tokens支持128字节，我导入文件需要做embedding时，文件的字符大于这个最大128tokens这个限制，需要CharacterTextSplitter chunk_size = 128来分割文件字符，这么小的分割，会不会对文章的语意切开的比较大，在向量相似度搜索时，会不会出现，搜索不到的情况？这个情况，建议怎么解决呢,谢谢

**Comment by shibing624** [comment]
分隔之后，前后句子拼接一下，句子1 的后面10个字符，在句子2的句首再写进去，后面同理。

**Comment by stoneLee81** [comment]
谢谢，我试一下
